server.port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test_db_1;INIT=RUNSCRIPT FROM 'classpath:sql/schema.sql'
#    username: sa
#    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        default_schema: sql/schema.sql


#  sql:
#    init:
#      mode: always

